build time -- 2022-07-03 02:48:01.917783

Inactive Modules:
  1) mpt/2.25

Due to MODULEPATH changes, the following have been reloaded:
  1) ncarcompilers/0.5.0

The following have been reloaded with a version change:
  1) intel/19.1.1 => intel/18.0.5     2) netcdf/4.8.1 => netcdf/4.6.3

+ export ESMF_NETCDF=nc-config
+ ESMF_NETCDF=nc-config
+ export ESMF_DIR=/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_O_develop
+ ESMF_DIR=/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_O_develop
+ export ESMF_COMPILER=intel
+ ESMF_COMPILER=intel
+ export ESMF_COMM=intelmpi
+ ESMF_COMM=intelmpi
+ export ESMF_BOPT=O
+ ESMF_BOPT=O
+ export ESMF_TESTEXHAUSTIVE=ON
+ ESMF_TESTEXHAUSTIVE=ON
+ export ESMF_TESTWITHTHREADS=ON
+ ESMF_TESTWITHTHREADS=ON
+ python3 setup.py test_examples_dryrun
running test_examples_dryrun
error: [Errno 2] No such file or directory: ''
+ python3 setup.py test_regrid_from_file_dryrun
running test_regrid_from_file_dryrun
Traceback (most recent call last):
  File "src/ESMF/test/regrid_from_file/run_regrid_from_file_dryrun.py", line 14, in <module>
    from ESMF.test.regrid_from_file.regrid_from_file_consts import DATA_SUBDIR, DATA_URL_ROOT
  File "/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_O_develop/src/addon/ESMPy/src/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_O_develop/src/addon/ESMPy/src/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_O_develop/src/addon/ESMPy/src/ESMF/interface/cbindings.py", line 13, in <module>
    from ESMF.interface.loadESMF import _ESMF
  File "/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_O_develop/src/addon/ESMPy/src/ESMF/interface/loadESMF.py", line 36, in <module>
    with open(esmfmk, 'r') as MKFILE:
FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "setup.py", line 278, in <module>
    'test_regrid_from_file_parallel': TestRegridFromFileParallelCommand})
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 197, in run
    subprocess.check_call(cmd)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/bin/python3', 'src/ESMF/test/regrid_from_file/run_regrid_from_file_dryrun.py']' returned non-zero exit status 1.
